Add blumenau dev day 2020
HackerspaceBlumenau/hackerspaceblumenau.github.io pull request #39
Opened 2020-11-11 22:28 UTC by rtancman

Add blumenau dev day 2020

- Fix 2019 event base url

2020-11-13 08:45 UTC, jaswdr requested changes

2020-11-13 08:45 UTC, jaswdr commented on blumenau-dev-day/2019/fonts/desktop.ini
> +[.ShellClassInfo]
Please remove this file

2020-11-13 08:45 UTC, jaswdr commented on blumenau-dev-day/2019/img/favicons/desktop.ini
> +[.ShellClassInfo]
Please remove this file

2020-11-13 08:45 UTC, jaswdr commented on blumenau-dev-day/2019/img/sprites/desktop.ini
> +[.ShellClassInfo]
Please remove this file

2020-11-13 18:23 UTC, alexandrevicenzi commented
O certo é fazer o site em outro repositorio. No caso o https://github.com/HackerspaceBlumenau/blumenaudevday, o FLISoL é assim.

2020-11-13 18:57 UTC, rtancman commented
> O certo é fazer o site em outro repositorio. No caso o https://github.com/HackerspaceBlumenau/blumenaudevday, o FLISoL é assim.
> 
> Se acessar https://www.hackerspaceblumenau.org/blumenaudevday/ funciona, mas tem algo zuado, nao carrega os CSS.

Eu vi é pq coloquei o `baseurl` com `-` ta assim  hj https://www.hackerspaceblumenau.org/blumenau-dev-day/ e deveria ser https://www.hackerspaceblumenau.org/blumenaudevday/ :trollface:

2020-11-13 23:06 UTC, alexandrevicenzi commented
Pra mudar a url precisa renomear o repositorio, se tu tem acesso manda bala, senão me avisa, podes chamar no Slack e podemos ajustar isso de forma rapida.

2020-11-17 12:01 UTC, alexandrevicenzi commented
@jvanz porque reabriu? não faz sentido colocar o site do blumenau dev day nesse repositorio.

2021-02-16 17:18 UTC, closed without merging